_BASE_: "Base-CD-AODN.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 0
  WEIGHTS: ''
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 3

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
#  STEPS: (27000,108000)
  STEPS: (31407,282633)
  MAX_ITER: 376884
  CHECKPOINT_PERIOD: 31407
INPUT:
  FORMAT: "RGB"

